### ISSUE TITLE
Input to processBlock should be const

### ISSUE THREAD

**Issue by salsa-sound** [klangfreund/LUFSMeter#5]
In the processBlock function you say "We want the audio output to be exactly the same as the input!" To ensure this and let the client know that their audio buffer will not be changed, the input to the function should be 'const juce::AudioSampleBuffer&'

**Comment by klangfreund** [comment]
Good point! Thank you for letting me know. It's now const.

https://github.com/klangfreund/LUFSMeter/commit/783a59d78c31e52b3a50b52d9afaadf3118f7536
